from turtle import *
hideturtle()
def skyScraper(width,height,x): #Kurt Leinemann, basic code for creating a skyscraper of varying height and width at any x position
	tower=Turtle()
	pencolor("black")
	fillcolor("gray")
	pensize(3)
	penup()
	goto(x,0)
	pendown()
	begin_fill()
	left(90)
	forward(height)
	right(90)
	forward(width)
	right(90)
	forward(height)
	right(90)
	forward(width)
	right(180)
	end_fill()
	hideturtle()
skyScraper(20,100,100)
skyScraper(50,180,0)
skyScraper(10,70,50)

def street(): #Kurt Leinemann. Its a black street with a double yellow line
	road=Turtle()
	penup()
	goto(-500,-40)
	pendown()
	pencolor("black")
	fillcolor("black")
	begin_fill()
	forward(1000)
	left(90)
	forward(40)
	left(90)
	forward(1000)
	left(90)
	forward(40)
	end_fill()
	streetLine(-20)
	streetLine(-15)
	
def streetLine(y): #(Kurt Leinemann) Function for use with street
	line=Turtle()
	left(90)
	penup()
	goto(-500,y)
	pencolor("yellow")
	pensize(2)
	pendown()
	forward(1000)
	right(90)
street()

