#Kurt, Frank, and Eli
#10-18-19
from turtle import *
import turtle
hideturtle()
def background():#Frank Carter, draws in a background for the cityscape
    penup()
    goto(-500,0)
    pendown()
    pencolor("blue")
    fillcolor("blue")
    begin_fill()
    forward(1000)
    left(90)
    forward(400)
    left(90)
    forward(1000)
    left(90)
    forward(400)
    end_fill()
    left(90)
background()
def skyScraper(width,height,x): #Kurt Leinemann, basic code for creating a skyscraper of varying height and width at any x position
	tower=Turtle()
	pencolor("black")
	fillcolor("gray")
	pensize(3)
	penup()
	goto(x,0)
	pendown()
	begin_fill()
	left(90)
	forward(height)
	right(90)
	forward(width)
	right(90)
	forward(height)
	right(90)
	forward(width)
	right(180)
	end_fill()
	hideturtle()
skyScraper(20,100,100)
skyScraper(50,180,0)
skyScraper(10,70,50)
skyScraper(40,80,-40)
skyScraper(10,80,-120)
skyScraper(20,60,-90)
skyScraper(40,110,180)
skyScraper(20,60,220)
skyScraper(40,80,60)
skyScraper(60,150,-330)
skyScraper(20,50,-160)
skyScraper(40,80,-40)
skyScraper(40,140,140)
skyScraper(30,120,-240)
skyScraper(50,90,-220)
skyScraper(20,110,-170)
skyScraper(20,110, 100)
skyScraper(30,70,260)
skyScraper(90,40,-130)
skyScraper(40,90,-70)

def street(): #Kurt Leinemann. Its a black street with a double yellow line
	road=Turtle()
	penup()
	goto(-500,-40)
	pendown()
	pencolor("black")
	fillcolor("black")
	begin_fill()
	forward(1000)
	left(90)
	forward(40)
	left(90)
	forward(1000)
	left(90)
	forward(40)
	end_fill()
	streetLine(-20)
	streetLine(-15)
	
def streetLine(y): #(Kurt Leinemann) Function for use with street
	line=Turtle()
	left(90)
	penup()
	goto(-500,y)
	pencolor("yellow")
	pensize(2)
	pendown()
	forward(1000)
	right(90)
street()

def foreground():#Frank Carter, draws in a foreground for the cityscape
    penup()
    goto(-500,-40)
    pendown()
    pencolor("green")
    fillcolor("green")
    begin_fill()
    left(90)
    forward(1000)
    right(90)
    forward(400)
    right(90)
    forward(1000)
    right(90)
    forward(400)
    end_fill()

foreground()
    
def tree(x,y):#Frank Carter, puts a tree in the foreground with inputted x and y values
    penup()
    goto(x,y)
    pendown()
    pencolor("black")
    fillcolor("brown")
    begin_fill()
    left(90)
    forward(20)
    left(90)
    forward(50)
    left(90)
    forward(20)
    left(90)
    forward(50)
    left(90)
    end_fill()
    penup()
    goto(x-10,y+10)
    pendown()
    pencolor("black")
    fillcolor("green")
    begin_fill()
    circle(15)
    end_fill()
    penup()
    goto(x,y)
    pendown()
    pencolor("black")
    fillcolor("green")
    begin_fill()
    circle(15)
    end_fill()
    penup()
    goto(x-20,y)
    pendown()
    pencolor("black")
    fillcolor("green")
    begin_fill()
    circle(15)
    end_fill()

tree(-300,-150)
tree(50,-100)
tree(100,-175)
tree(-50,-120)
tree(-130,-190)
tree(250, -70)
    
#Eli, This function creates a car on the road at any x-position
def car(x):
    cars=turtle.Turtle()
    cars.ht()
    cars.penup()
    cars.goto(x,-37)
    cars.pendown()
    cars.pencolor("black")
    cars.begin_fill()
    cars.circle(6)
    cars.fillcolor("silver")
    cars.end_fill()
    cars.penup()
    cars.goto(x+30,-37)
    cars.pendown()
    cars.pencolor("black")
    cars.begin_fill()
    cars.circle(6)
    cars.fillcolor("silver")
    cars.end_fill()
    cars.right(90)
    cars.penup()
    cars.goto(x+10,-28)
    cars.left(90)
    cars.pendown()
    cars.pencolor("black")
    cars.begin_fill()
    cars.forward(35)
    cars.left(90)
    cars.forward(10)
    cars.left(90)
    cars.forward(10)
    cars.right(90)
    cars.forward(20)
    cars.left(90)
    cars.forward(30)
    cars.left(90)
    cars.forward(20)
    cars.right(90)
    cars.forward(10)
    cars.left(90)
    cars.forward(10)
    cars.left(90)
    cars.forward(20)
    cars.fillcolor("red")
    cars.end_fill()
    cars.penup()
    cars.goto(x+25,-20)
    cars.pendown()
    cars.pencolor("black")
    cars.begin_fill()
    cars.forward(10)
    cars.left(90)
    cars.forward(17)
    cars.left(90)
    cars.forward(20)
    cars.left(90)
    cars.forward(17)
    cars.left(90)
    cars.forward(10)
    cars.fillcolor("light grey")
    cars.end_fill()
car(0)
car(100)
car(-200)




    

